version: '3.9'

volumes:
  pg_data:

services:
  db:
    image: postgis/postgis
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME

  adminer:
    image: adminer
    restart: always
    ports:
      - '1081:8080'
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce file-upload'
      ADMINER_DESIGN: 'dracula'
