
curl -X 'POST' \
  'http://localhost:3000/api/v1/termsandconditions' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5ZGNmNmM5LTVlNGUtNDIxMy04YjNjLTc2ZGQzMzNjZjc3OCIsImlhdCI6MTYzNzkwMjQ4OSwiZXhwIjoxNjM3OTg4ODg5fQ.rSXxF3tGDuTgEY_IArzZlcvEX7rzME4Q3sj7y3Z1_NM' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": "cbcfa8b8-2a25-3adb-a9c6-e325f0d0f3ae",
  "type_name": "Sample FAQ 1",
  "text_content": "FAQ 1 sample description"
}'

###
curl -X 'GET' \
  'http://localhost:3000/api/v1/termsandconditions' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5ZGNmNmM5LTVlNGUtNDIxMy04YjNjLTc2ZGQzMzNjZjc3OCIsImlhdCI6MTYzNzkwMjQ4OSwiZXhwIjoxNjM3OTg4ODg5fQ.rSXxF3tGDuTgEY_IArzZlcvEX7rzME4Q3sj7y3Z1_NM'